### ISSUE TITLE
Link images to fumen

### ISSUE THREAD

**Issue by eight04** [knewjade/tsd-opener#1]
Therefore, users can open each setup in a new tab and investigate continuations.

**Comment by knewjade** [comment]
OK 👌 I will do later (It may take some time because I have other works)

**Comment by knewjade** [comment]
I did it. 

![Jan-19-2020 20-49-22](https://user-images.githubusercontent.com/27051545/72680438-31829600-3afd-11ea-9a9b-1a06baf1913b.gif)
